import { describe, expect, it } from "vitest";
import { render, screen, userEvent } from "@/test/utils";

import { MarkdownRenderer } from "./MarkdownRenderer";

// CHAOS-7788: the report page has its own h1 (the report name) and the body sits
// under the card heading (h2), so the report markdown renders two heading levels
// down and never adds a second h1.
const REPORT = [
    "# Weekly Health Report",
    "",
    "## Summary",
    "",
    "Text.",
    "",
    "### Insights",
    "",
    "#### Detail",
    "",
    "##### Note",
    "",
    "###### Smallest",
    "",
    "## Provenance",
    "",
    "# Sources",
    "",
    "## Inputs",
    "",
    "---",
    "Generated by the report service.",
].join("\n");

describe("MarkdownRenderer headings (CHAOS-7788)", () => {
    it("renders each report heading two levels down", async () => {
        render(<MarkdownRenderer content={REPORT} />);

        expect(
            await screen.findByRole("heading", { level: 3, name: "Weekly Health Report" }),
        ).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 4, name: "Summary" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 5, name: "Insights" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 6, name: "Detail" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 6, name: "Note" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 6, name: "Smallest" })).toBeInTheDocument();
    });

    it("keeps the look of the source level: `###` is still drawn as a heading", async () => {
        render(<MarkdownRenderer content={REPORT} />);

        const look = (name: string) =>
            screen.getByRole("heading", { name }).className.split(/\s+/).filter(Boolean);
        await screen.findByRole("heading", { name: "Weekly Health Report" });

        // The prose-sm look of h1, h2, h3, h4, with the prose heading color.
        expect(look("Weekly Health Report")).toEqual(
            expect.arrayContaining(["text-3xl", "font-extrabold", "text-(--tw-prose-headings)"]),
        );
        expect(look("Summary")).toEqual(
            expect.arrayContaining(["text-xl", "font-bold", "text-(--tw-prose-headings)"]),
        );
        expect(look("Insights")).toEqual(
            expect.arrayContaining(["text-lg", "font-semibold", "text-(--tw-prose-headings)"]),
        );
        expect(look("Detail")).toEqual(
            expect.arrayContaining(["text-sm", "font-semibold", "text-(--tw-prose-headings)"]),
        );
        // `#####` and `######` had no prose style and get none.
        expect(look("Note")).toEqual([]);
        expect(look("Smallest")).toEqual([]);
        // The markdown node is not passed to the DOM.
        expect(screen.getByRole("heading", { name: "Insights" })).not.toHaveAttribute("node");
    });

    it("never renders an h1", async () => {
        const { container } = render(<MarkdownRenderer content={REPORT} />);

        await screen.findByRole("heading", { name: "Weekly Health Report" });
        expect(container.querySelectorAll("h1")).toHaveLength(0);
    });

    it("shifts the headings of the provenance part too", async () => {
        const user = userEvent.setup();
        const { container } = render(<MarkdownRenderer content={REPORT} />);

        await user.click(screen.getByRole("button", { name: "Provenance" }));

        expect(
            await screen.findByRole("heading", { level: 3, name: "Sources" }),
        ).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 4, name: "Inputs" })).toBeInTheDocument();
        // The provenance part keeps the base prose look of its source level.
        expect(screen.getByRole("heading", { name: "Sources" })).toHaveClass("text-4xl");
        expect(screen.getByRole("heading", { name: "Inputs" })).toHaveClass("text-2xl");
        expect(container.querySelectorAll("h1")).toHaveLength(0);
        expect(screen.getByText("Generated by the report service.")).toBeInTheDocument();
    });
});
