import { describe, expect, it } from "vitest";
import { render, screen, userEvent } from "@/test/utils";

import { MarkdownRenderer } from "./MarkdownRenderer";

// CHAOS-7788: the report page has its own h1 (the report name), so the report
// markdown renders one heading level down and never adds a second h1.
const REPORT = [
    "# Weekly Health Report",
    "",
    "## Summary",
    "",
    "Text.",
    "",
    "### Insights",
    "",
    "#### Detail",
    "",
    "##### Note",
    "",
    "###### Smallest",
    "",
    "## Provenance",
    "",
    "# Sources",
    "",
    "## Inputs",
    "",
    "---",
    "Generated by the report service.",
].join("\n");

describe("MarkdownRenderer headings (CHAOS-7788)", () => {
    it("renders each report heading one level down", async () => {
        render(<MarkdownRenderer content={REPORT} />);

        expect(
            await screen.findByRole("heading", { level: 2, name: "Weekly Health Report" }),
        ).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 3, name: "Summary" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 4, name: "Insights" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 5, name: "Detail" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 6, name: "Note" })).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 6, name: "Smallest" })).toBeInTheDocument();
    });

    it("never renders an h1", async () => {
        const { container } = render(<MarkdownRenderer content={REPORT} />);

        await screen.findByRole("heading", { name: "Weekly Health Report" });
        expect(container.querySelectorAll("h1")).toHaveLength(0);
    });

    it("shifts the headings of the provenance part too", async () => {
        const user = userEvent.setup();
        const { container } = render(<MarkdownRenderer content={REPORT} />);

        await user.click(screen.getByRole("button", { name: "Provenance" }));

        expect(
            await screen.findByRole("heading", { level: 2, name: "Sources" }),
        ).toBeInTheDocument();
        expect(screen.getByRole("heading", { level: 3, name: "Inputs" })).toBeInTheDocument();
        expect(container.querySelectorAll("h1")).toHaveLength(0);
        expect(screen.getByText("Generated by the report service.")).toBeInTheDocument();
    });
});
