/* eslint-disable */
import * as types from './graphql';



/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "query GetConnectorsDataHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    connectors {\n      provider\n      scope\n      lastSyncAt\n      rowsIngested\n      lastFailure {\n        occurredAt\n        message\n        stage\n      }\n    }\n  }\n}": typeof types.GetConnectorsDataHealthDocument,
    "query DataHealthIdentity($team: ID!) {\n  dataHealth(team: $team) {\n    identityMapping {\n      unmappedCount\n      unmappedIdentities {\n        provider\n        email\n        displayName\n        observedCount\n      }\n      suggestedAliases {\n        unmappedIdentity {\n          provider\n          email\n          displayName\n        }\n        suggestedCanonicalId\n        suggestedCanonicalName\n        confidence\n      }\n    }\n  }\n}": typeof types.DataHealthIdentityDocument,
    "query MetricLineage($metricId: ID!) {\n  dataHealth(team: \"ALL\") {\n    metricLineage(metricId: $metricId) {\n      metricId\n      sourceTables\n      computeWindow {\n        kind\n        durationDays\n      }\n      computedAt\n      rowCount\n    }\n  }\n}": typeof types.MetricLineageDocument,
    "query GetMappingCoverageHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    mappingCoverage {\n      deployments {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n      workItems {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n    }\n  }\n}": typeof types.GetMappingCoverageHealthDocument,
    "query CompoundingRisk($orgId: String!, $filter: CompoundingRiskFilterInput = null) {\n  compoundingRisk(orgId: $orgId, filter: $filter) {\n    orgId\n    breakout\n    generatedAt\n    rows {\n      day\n      scope\n      scopeId\n      scopeLabel\n      score\n      coverage\n      severity\n      computedAt\n      components {\n        churnNorm\n        complexityNorm\n        ownershipNorm\n        reviewNorm\n        reworkChurn\n        complexityDelta\n        ownershipGini\n        singleOwnerRatio\n        reviewLatencyP90h\n        __typename\n      }\n      weights {\n        churn\n        complexity\n        ownership\n        review\n        __typename\n      }\n      thresholds {\n        elevated\n        high\n        __typename\n      }\n      __typename\n    }\n    trend {\n      day\n      score\n      severity\n      __typename\n    }\n    __typename\n  }\n}": typeof types.CompoundingRiskDocument,
    "query Home($orgId: String!, $filters: FilterInput, $window: HomeWindowInput) {\n  home(orgId: $orgId, filters: $filters, window: $window) {\n    freshness {\n      lastIngestedAt\n      latestSuccessfulSyncAt\n      sources {\n        provider\n        status\n        __typename\n      }\n      coverage {\n        reposCoveredPct\n        prsLinkedToIssuesPct\n        issuesWithCycleStatesPct\n        __typename\n      }\n      __typename\n    }\n    deltas {\n      metric\n      label\n      value\n      unit\n      deltaPct\n      hasData\n      hasPriorData\n      spark {\n        ts\n        value\n        __typename\n      }\n      rateState\n      rateCoverage\n      repoFilterApplied\n      repoLinkState\n      repoLinkBasis {\n        native\n        explicitText\n        heuristic\n        __typename\n      }\n      repoLinkMultiRepoItems\n      repoLinkCoverage {\n        linkedItems\n        itemsInWindow\n        __typename\n      }\n      __typename\n    }\n    reworkThemeAllocation {\n      theme\n      label\n      allocation\n      allocationPct\n      prsMerged\n      churnLoc\n      __typename\n    }\n    summary {\n      id\n      text\n      evidenceLink\n      __typename\n    }\n    tiles {\n      key\n      value {\n        title\n        subtitle\n        link\n        __typename\n      }\n      __typename\n    }\n    constraint {\n      title\n      claim\n      evidence {\n        label\n        link\n        __typename\n      }\n      experiments\n      __typename\n    }\n    events {\n      ts\n      type\n      text\n      link\n      __typename\n    }\n    healthState {\n      status\n      headline\n      summary\n      asOf\n      __typename\n    }\n    signals {\n      id\n      title\n      metric\n      currentValue\n      priorValue\n      delta\n      direction\n      severity\n      confidence\n      affectedScope\n      evidenceCount\n      whyItMatters\n      recommendedAction\n      evidenceRef\n      category\n      scopeEntity {\n        id\n        displayName\n        __typename\n      }\n      coverage\n      repoFilterApplied\n      attribution {\n        items\n        sources {\n          source\n          items\n          share\n          __typename\n        }\n        confidence {\n          confidence\n          items\n          share\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    limitingFactor {\n      claim\n      whyItMatters\n      recommendedAction\n      confidence\n      evidenceRef\n      __typename\n    }\n    dataConfidence {\n      level\n      coveragePct\n      connectedSources\n      missingSources\n      caveats\n      __typename\n    }\n    scopeDataConfidence {\n      level\n      coveragePct\n      lastIngestedAt\n      caveats\n      __typename\n    }\n    __typename\n  }\n}": typeof types.HomeDocument,
};
const documents: Documents = {
    "query GetConnectorsDataHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    connectors {\n      provider\n      scope\n      lastSyncAt\n      rowsIngested\n      lastFailure {\n        occurredAt\n        message\n        stage\n      }\n    }\n  }\n}": types.GetConnectorsDataHealthDocument,
    "query DataHealthIdentity($team: ID!) {\n  dataHealth(team: $team) {\n    identityMapping {\n      unmappedCount\n      unmappedIdentities {\n        provider\n        email\n        displayName\n        observedCount\n      }\n      suggestedAliases {\n        unmappedIdentity {\n          provider\n          email\n          displayName\n        }\n        suggestedCanonicalId\n        suggestedCanonicalName\n        confidence\n      }\n    }\n  }\n}": types.DataHealthIdentityDocument,
    "query MetricLineage($metricId: ID!) {\n  dataHealth(team: \"ALL\") {\n    metricLineage(metricId: $metricId) {\n      metricId\n      sourceTables\n      computeWindow {\n        kind\n        durationDays\n      }\n      computedAt\n      rowCount\n    }\n  }\n}": types.MetricLineageDocument,
    "query GetMappingCoverageHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    mappingCoverage {\n      deployments {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n      workItems {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n    }\n  }\n}": types.GetMappingCoverageHealthDocument,
    "query CompoundingRisk($orgId: String!, $filter: CompoundingRiskFilterInput = null) {\n  compoundingRisk(orgId: $orgId, filter: $filter) {\n    orgId\n    breakout\n    generatedAt\n    rows {\n      day\n      scope\n      scopeId\n      scopeLabel\n      score\n      coverage\n      severity\n      computedAt\n      components {\n        churnNorm\n        complexityNorm\n        ownershipNorm\n        reviewNorm\n        reworkChurn\n        complexityDelta\n        ownershipGini\n        singleOwnerRatio\n        reviewLatencyP90h\n        __typename\n      }\n      weights {\n        churn\n        complexity\n        ownership\n        review\n        __typename\n      }\n      thresholds {\n        elevated\n        high\n        __typename\n      }\n      __typename\n    }\n    trend {\n      day\n      score\n      severity\n      __typename\n    }\n    __typename\n  }\n}": types.CompoundingRiskDocument,
    "query Home($orgId: String!, $filters: FilterInput, $window: HomeWindowInput) {\n  home(orgId: $orgId, filters: $filters, window: $window) {\n    freshness {\n      lastIngestedAt\n      latestSuccessfulSyncAt\n      sources {\n        provider\n        status\n        __typename\n      }\n      coverage {\n        reposCoveredPct\n        prsLinkedToIssuesPct\n        issuesWithCycleStatesPct\n        __typename\n      }\n      __typename\n    }\n    deltas {\n      metric\n      label\n      value\n      unit\n      deltaPct\n      hasData\n      hasPriorData\n      spark {\n        ts\n        value\n        __typename\n      }\n      rateState\n      rateCoverage\n      repoFilterApplied\n      repoLinkState\n      repoLinkBasis {\n        native\n        explicitText\n        heuristic\n        __typename\n      }\n      repoLinkMultiRepoItems\n      repoLinkCoverage {\n        linkedItems\n        itemsInWindow\n        __typename\n      }\n      __typename\n    }\n    reworkThemeAllocation {\n      theme\n      label\n      allocation\n      allocationPct\n      prsMerged\n      churnLoc\n      __typename\n    }\n    summary {\n      id\n      text\n      evidenceLink\n      __typename\n    }\n    tiles {\n      key\n      value {\n        title\n        subtitle\n        link\n        __typename\n      }\n      __typename\n    }\n    constraint {\n      title\n      claim\n      evidence {\n        label\n        link\n        __typename\n      }\n      experiments\n      __typename\n    }\n    events {\n      ts\n      type\n      text\n      link\n      __typename\n    }\n    healthState {\n      status\n      headline\n      summary\n      asOf\n      __typename\n    }\n    signals {\n      id\n      title\n      metric\n      currentValue\n      priorValue\n      delta\n      direction\n      severity\n      confidence\n      affectedScope\n      evidenceCount\n      whyItMatters\n      recommendedAction\n      evidenceRef\n      category\n      scopeEntity {\n        id\n        displayName\n        __typename\n      }\n      coverage\n      repoFilterApplied\n      attribution {\n        items\n        sources {\n          source\n          items\n          share\n          __typename\n        }\n        confidence {\n          confidence\n          items\n          share\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    limitingFactor {\n      claim\n      whyItMatters\n      recommendedAction\n      confidence\n      evidenceRef\n      __typename\n    }\n    dataConfidence {\n      level\n      coveragePct\n      connectedSources\n      missingSources\n      caveats\n      __typename\n    }\n    scopeDataConfidence {\n      level\n      coveragePct\n      lastIngestedAt\n      caveats\n      __typename\n    }\n    __typename\n  }\n}": types.HomeDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetConnectorsDataHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    connectors {\n      provider\n      scope\n      lastSyncAt\n      rowsIngested\n      lastFailure {\n        occurredAt\n        message\n        stage\n      }\n    }\n  }\n}"): typeof import('./graphql').GetConnectorsDataHealthDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query DataHealthIdentity($team: ID!) {\n  dataHealth(team: $team) {\n    identityMapping {\n      unmappedCount\n      unmappedIdentities {\n        provider\n        email\n        displayName\n        observedCount\n      }\n      suggestedAliases {\n        unmappedIdentity {\n          provider\n          email\n          displayName\n        }\n        suggestedCanonicalId\n        suggestedCanonicalName\n        confidence\n      }\n    }\n  }\n}"): typeof import('./graphql').DataHealthIdentityDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query MetricLineage($metricId: ID!) {\n  dataHealth(team: \"ALL\") {\n    metricLineage(metricId: $metricId) {\n      metricId\n      sourceTables\n      computeWindow {\n        kind\n        durationDays\n      }\n      computedAt\n      rowCount\n    }\n  }\n}"): typeof import('./graphql').MetricLineageDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetMappingCoverageHealth($teamId: ID!) {\n  dataHealth(team: $teamId) {\n    mappingCoverage {\n      deployments {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n      workItems {\n        totalRepos\n        coveredRepos\n        coveragePct\n      }\n    }\n  }\n}"): typeof import('./graphql').GetMappingCoverageHealthDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query CompoundingRisk($orgId: String!, $filter: CompoundingRiskFilterInput = null) {\n  compoundingRisk(orgId: $orgId, filter: $filter) {\n    orgId\n    breakout\n    generatedAt\n    rows {\n      day\n      scope\n      scopeId\n      scopeLabel\n      score\n      coverage\n      severity\n      computedAt\n      components {\n        churnNorm\n        complexityNorm\n        ownershipNorm\n        reviewNorm\n        reworkChurn\n        complexityDelta\n        ownershipGini\n        singleOwnerRatio\n        reviewLatencyP90h\n        __typename\n      }\n      weights {\n        churn\n        complexity\n        ownership\n        review\n        __typename\n      }\n      thresholds {\n        elevated\n        high\n        __typename\n      }\n      __typename\n    }\n    trend {\n      day\n      score\n      severity\n      __typename\n    }\n    __typename\n  }\n}"): typeof import('./graphql').CompoundingRiskDocument;
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query Home($orgId: String!, $filters: FilterInput, $window: HomeWindowInput) {\n  home(orgId: $orgId, filters: $filters, window: $window) {\n    freshness {\n      lastIngestedAt\n      latestSuccessfulSyncAt\n      sources {\n        provider\n        status\n        __typename\n      }\n      coverage {\n        reposCoveredPct\n        prsLinkedToIssuesPct\n        issuesWithCycleStatesPct\n        __typename\n      }\n      __typename\n    }\n    deltas {\n      metric\n      label\n      value\n      unit\n      deltaPct\n      hasData\n      hasPriorData\n      spark {\n        ts\n        value\n        __typename\n      }\n      rateState\n      rateCoverage\n      repoFilterApplied\n      repoLinkState\n      repoLinkBasis {\n        native\n        explicitText\n        heuristic\n        __typename\n      }\n      repoLinkMultiRepoItems\n      repoLinkCoverage {\n        linkedItems\n        itemsInWindow\n        __typename\n      }\n      __typename\n    }\n    reworkThemeAllocation {\n      theme\n      label\n      allocation\n      allocationPct\n      prsMerged\n      churnLoc\n      __typename\n    }\n    summary {\n      id\n      text\n      evidenceLink\n      __typename\n    }\n    tiles {\n      key\n      value {\n        title\n        subtitle\n        link\n        __typename\n      }\n      __typename\n    }\n    constraint {\n      title\n      claim\n      evidence {\n        label\n        link\n        __typename\n      }\n      experiments\n      __typename\n    }\n    events {\n      ts\n      type\n      text\n      link\n      __typename\n    }\n    healthState {\n      status\n      headline\n      summary\n      asOf\n      __typename\n    }\n    signals {\n      id\n      title\n      metric\n      currentValue\n      priorValue\n      delta\n      direction\n      severity\n      confidence\n      affectedScope\n      evidenceCount\n      whyItMatters\n      recommendedAction\n      evidenceRef\n      category\n      scopeEntity {\n        id\n        displayName\n        __typename\n      }\n      coverage\n      repoFilterApplied\n      attribution {\n        items\n        sources {\n          source\n          items\n          share\n          __typename\n        }\n        confidence {\n          confidence\n          items\n          share\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    limitingFactor {\n      claim\n      whyItMatters\n      recommendedAction\n      confidence\n      evidenceRef\n      __typename\n    }\n    dataConfidence {\n      level\n      coveragePct\n      connectedSources\n      missingSources\n      caveats\n      __typename\n    }\n    scopeDataConfidence {\n      level\n      coveragePct\n      lastIngestedAt\n      caveats\n      __typename\n    }\n    __typename\n  }\n}"): typeof import('./graphql').HomeDocument;


export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}
