export const iaPreservationBaseline = {
	navVisibleDestinations: [
		{
			areaId: "diagnose",
			childId: "diagnose-overview",
			label: "Overview",
			path: "/work",
		},
		{
			areaId: "diagnose",
			childId: "work",
			label: "Work",
			path: "/work?view=work",
		},
		{ areaId: "diagnose", childId: "flow", label: "Flow", path: "/metrics" },
		{
			areaId: "diagnose",
			childId: "investment",
			label: "Investment",
			path: "/investment",
		},
		{
			areaId: "diagnose",
			childId: "landscape",
			label: "Landscape",
			path: "/landscape",
		},
		{ areaId: "diagnose", childId: "people", label: "People", path: "/people" },
		{ areaId: "diagnose", childId: "code", label: "Code", path: "/code" },
		{
			areaId: "diagnose",
			childId: "complexity",
			label: "Complexity",
			path: "/complexity",
		},
		{
			areaId: "diagnose",
			childId: "cognitive-load",
			label: "Cognitive Load",
			path: "/cognitive-load",
		},
		{
			areaId: "diagnose",
			childId: "bottleneck",
			label: "Bottlenecks",
			path: "/bottleneck",
		},
		{
			areaId: "plan",
			childId: "plan-overview",
			label: "Overview",
			path: "/plan",
		},
		{
			areaId: "plan",
			childId: "delivery-forecast",
			label: "Delivery Forecast",
			path: "/plan/delivery-forecast",
		},
		{
			areaId: "plan",
			childId: "capacity",
			label: "Capacity",
			path: "/plan/capacity",
		},
		{
			areaId: "plan",
			childId: "operating-review",
			label: "Operating Review",
			path: "/operating-review",
		},
		{
			areaId: "improve",
			childId: "opportunities",
			label: "Opportunities",
			path: "/opportunities",
		},
		{
			areaId: "govern",
			childId: "testops",
			label: "Overview",
			path: "/testops",
		},
		{
			areaId: "govern",
			childId: "pipelines",
			label: "Pipelines",
			path: "/testops/pipelines",
		},
		{
			areaId: "govern",
			childId: "tests",
			label: "Tests",
			path: "/testops/tests",
		},
		{
			areaId: "govern",
			childId: "quality",
			label: "Quality",
			path: "/quality",
		},
		{
			areaId: "govern",
			childId: "coverage",
			label: "Coverage",
			path: "/testops/coverage",
		},
		{
			areaId: "govern",
			childId: "risk",
			label: "Delivery Risk",
			path: "/testops/risk",
		},
		{
			areaId: "govern",
			childId: "incident-correlation",
			label: "Incident Correlation",
			path: "/incident-correlation",
		},
		{
			areaId: "govern",
			childId: "security",
			label: "Security",
			path: "/security",
		},
		{
			areaId: "govern",
			childId: "feature-flags",
			label: "Feature Flags",
			path: "/feature-flags",
		},
		{
			areaId: "govern",
			childId: "risk-compounding",
			label: "Compounding Risk",
			path: "/risk/compounding",
		},
		{ areaId: "ai", childId: "ai-overview", label: "Overview", path: "/ai" },
		{ areaId: "ai", childId: "ai-impact", label: "Impact", path: "/ai/impact" },
		{
			areaId: "ai",
			childId: "ai-review-load",
			label: "Review Load",
			path: "/ai/review-load",
		},
		{
			areaId: "ai",
			childId: "ai-governance-risk",
			label: "Governance Risk",
			path: "/ai/risk",
		},
		{
			areaId: "ai",
			childId: "ai-automations",
			label: "Automations",
			path: "/ai/automations",
		},
		{
			areaId: "reports",
			childId: "report-center",
			label: "Report Center",
			path: "/reports",
		},
		{
			areaId: "admin",
			childId: "organization",
			label: "Organization",
			path: "/admin",
		},
		{
			areaId: "admin",
			childId: "connections",
			label: "Connections",
			path: "/admin/sync",
		},
		{
			areaId: "admin",
			childId: "data-confidence",
			label: "Data Confidence",
			path: "/data-health",
		},
		{
			areaId: "admin",
			childId: "settings",
			label: "Settings",
			path: "/settings",
		},
	],
	workWorkbenchViews: [
		{ tab: "landscape", href: "/work?tab=landscape" },
		{ tab: "heatmap", href: "/work?tab=heatmap" },
		{ tab: "flow", href: "/work?tab=flow" },
		{ tab: "investment", href: "/work?tab=investment" },
		{ tab: "capacity", href: "/work?tab=capacity" },
		{ tab: "flame", href: "/work?tab=flame" },
		{ tab: "evidence", href: "/work?tab=evidence" },
		{ tab: "graph", href: "/work?tab=graph" },
	],
	investigationDeepLinks: [
		{
			source: "InvestigationPanel",
			intent: "cycle breakdown flame view",
			href: "/work?tab=flame&mode=cycle_breakdown",
			expectedTab: "flame",
		},
		{
			source: "InvestigationPanel",
			intent: "throughput flame view",
			href: "/work?tab=flame&mode=throughput",
			expectedTab: "flame",
		},
		{
			source: "InvestigationPanel",
			intent: "code hotspots flame view",
			href: "/work?tab=flame&mode=code_hotspots",
			expectedTab: "flame",
		},
		{
			source: "InvestigationPanel",
			intent: "related patterns heatmap view",
			href: "/work?tab=heatmap",
			expectedTab: "heatmap",
		},
		{
			source: "FlowView",
			intent: "selected node flame view",
			href: "/work?tab=flame&mode=throughput&context_node=Selected%20Node",
			expectedTab: "flame",
		},
		{
			source: "FlowView/InspectPanel",
			intent: "work graph view",
			href: "/work?tab=graph",
			expectedTab: "graph",
		},
		{
			source: "LandscapeView",
			intent: "flow view",
			href: "/work?tab=flow",
			expectedTab: "flow",
		},
	],
} as const;
